apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: customer
  template:
    metadata:
      name: customer
      labels:
        name: customer
    spec:
      containers:
        - name: customer
          image: customer-service
          ports:
            - containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    name: customer
  ports:
    - port: 80
      targetPort: 8084

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-ingress
  labels:
    name: customer-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "customer.local"
    http:
      paths:
      - path: "/"
        pathType: "Prefix"
        backend:
          service:
            name: customer-service
            port:
              number: 80